### ISSUE TITLE
MPD clients freeze after extended play time with Mopidy

### ISSUE THREAD

**Issue by muni-corn** [mopidy/mopidy-mpd#21]
This issue is with Mopidy 2.2.2.

After a while of playing music (with the spotify and spotify-web extensions), all MPD clients will freeze. Mopidy will play the next song, but the change won't be reflected by the client.

For example, after Song One, Mopidy will audibly play Song Two without a problem, but clients will still read "Song One" until restarted. When restarted, clients will read "Song Two," until Mopidy plays Song Three, when clients will read "Song Two." So, even after clients are restarted, changes to playback won't be registered. Pause/play events don't seem to be recognized either.

I dug into `journalctl` and found this error:

```
Mar 08 15:12:45 hotpocket mopidy[27779]: ERROR    Unhandled exception in MpdFrontend (urn:uuid:c1ea0816-6929-494c-a303-aea5a71a4fca):
Mar 08 15:12:45 hotpocket mopidy[27779]: Traceback (most recent call last):
Mar 08 15:12:45 hotpocket mopidy[27779]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
Mar 08 15:12:45 hotpocket mopidy[27779]:     response = self._handle_receive(message)
Mar 08 15:12:45 hotpocket mopidy[27779]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
Mar 08 15:12:45 hotpocket mopidy[27779]:     return callee(*message['args'], **message['kwargs'])
Mar 08 15:12:45 hotpocket mopidy[27779]:   File "/usr/lib/python2.7/site-packages/mopidy/mpd/actor.py", line 90, in on_event
Mar 08 15:12:45 hotpocket mopidy[27779]:     self.send_idle(_CORE_EVENTS_TO_IDLE_SUBSYSTEMS[event])
Mar 08 15:12:45 hotpocket mopidy[27779]:   File "/usr/lib/python2.7/site-packages/mopidy/mpd/actor.py", line 94, in send_idle
Mar 08 15:12:45 hotpocket mopidy[27779]:     listener.send(session.MpdSession, subsystem)
Mar 08 15:12:45 hotpocket mopidy[27779]:   File "/usr/lib/python2.7/site-packages/mopidy/listener.py", line 27, in send
Mar 08 15:12:45 hotpocket mopidy[27779]:     'kwargs': kwargs,
Mar 08 15:12:45 hotpocket mopidy[27779]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 398, in tell
Mar 08 15:12:45 hotpocket mopidy[27779]:     raise ActorDeadError('%s not found' % self)
Mar 08 15:12:45 hotpocket mopidy[27779]: ActorDeadError: MpdSession (urn:uuid:f383a206-85da-422f-81f1-c88ddcbf436f) not found
```

**Comment by jodal** [comment]
> *This was generated by AI during triage.*

This was reported with Mopidy 2.2.2 on Python 2, and there has been no activity since 2019. Mopidy-MPD has been rewritten a lot since then. Please open a new issue with a debug log if MPD clients still stop updating with the current versions. Closing.
